<?php

$title = 'My things';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('thing', array('action'=>'add'));?>">Add new thing</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($things as $thing) : ?>
<tr>
    <td><?php echo $this->escapeHtml($thing->title);?></td>
    <td><?php echo $this->escapeHtml($thing->artist);?></td>
    <td>
        <a href="<?php echo $this->url('thing',
            array('action'=>'edit', 'id' => $thing->id));?>">Edit</a>
        <a href="<?php echo $this->url('thing',
            array('action'=>'delete', 'id' => $thing->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
